services:
  # Database
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: mermaid_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432" # Host 5434 -> Container 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mermaid_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Auth service
  sb:
    # Use a pre-built JDK image instead of building a local Dockerfile
    image: eclipse-temurin:17-jdk-alpine 
    container_name: springboot_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/mermaid_db
      - DB_USER=user
      - DB_PASS=password
      - JWT_SECRET=Zm9ydHktdHdvLWlzLXRoZS1hbnN3ZXItdG8tbGlmZS10aGUtdW5pdmVyc2UtYW5kLWV2ZXJ5dGhpbmc=
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - .:/app              # Maps your local backend folder to /app in the container
      - ~/.m2:/root/.m2     # Caches Maven dependencies in your WSL home
    working_dir: /app
    # The container starts, sees your files via the volume, and runs them
    command: ./mvnw spring-boot:run

  react:
    image: node:20-alpine
    container_name: react_front
    depends_on:
      - sb
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../react:/app        # Go up one folder, then into the react folder
      - /app/node_modules
    working_dir: /app
    # Install linux-compatible node_modules on startup before running dev server
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  postgres_data: #persist db data