-- Fix admin seed password: set hash that matches "password" (BCrypt cost 10, generated by app encoder).
-- Run once; safe to re-run (UPDATE affects only admin@mermaid.local).

UPDATE users
SET password_hash = '$2a$10$SUokQtilFJbm9NAh95.u4OPukESygI.ahb4IjGHflC1FuSIBUEVxa',
    updated_at = now()
WHERE email = 'admin@mermaid.local';
